mepo.d/cmdline/parser.py, mepo.d/command/branch/brlist/brlist.py, mepo.d/command/branch/create/create.py, mepo.d/command/branch/delete/delete.py, mepo.d/command/checkout/checkout.py, mepo.d/command/clone/clone.py, mepo.d/command/commit/commit.py, mepo.d/command/develop/develop.py, mepo.d/command/push/push.py, mepo.d/command/save/save.py, mepo.d/command/stage/stage.py, mepo.d/command/status/status.py, mepo.d/command/unstage/unstage.py, mepo.d/repository/git.py, mepo.d/utilities/version.py
=> Consolidated git commands in a single class

mepo.d/cmdline/parser.py, mepo.d/command/diff/diff.py, mepo.d/repository/git.py
This is a first attempt at making a `mepo diff` command.
=> Fixes #20. Add mepo diff

mepo.d/cmdline/parser.py, mepo.d/command/compare/compare.py, mepo.d/command/diff/diff.py, mepo.d/repository/git.py
Also, prettify the compare output
=> Fixes #37. Add --name-only option for diff

mepo.d/cmdline/parser.py, mepo.d/command/fetch/fetch.py, mepo.d/repository/git.py
This commit should add `mepo fetch` and `mepo fetch --all`.
=> Fixes #52. Add fetch

mepo
Accidentally pulled in a forced shebang
=> Fix bad shebang

mepo.d/cmdline/stash_parser.py, mepo.d/command/stash/stash.py, mepo.d/command/stash/stshow/stshow.py, mepo.d/repository/git.py
I forgot to add `stash show`. Weirdly, I just cannot get color from the regular `git stash show` call.
=> Add stash show command

mepo.d/cmdline/parser.py, mepo.d/command/clone/clone.py, mepo.d/repository/git.py, mepo.d/utest/test_mepo_commands.py
=> Merge develop into main

.zenodo.json
Add a `.zenodo.json` file for more control over zenodo.
=> Add zenodo file

mepo.d/cmdline/parser.py, mepo.d/cmdline/stash_parser.py, mepo.d/cmdline/tag_parser.py, mepo.d/command/push/push.py, mepo.d/command/tag/create/create.py, mepo.d/command/tag/delete/delete.py, mepo.d/command/tag/tag.py, mepo.d/command/tag/tglist/tglist.py, mepo.d/repository/git.py
This PR adds:
```
mepo tag list
mepo tag create
mepo tag delete
```
I really only wanted a `tag list` command, but once the `tag` command exists, it may as well do other things.
=> Add tag commands

mepo.d/cmdline/parser.py, mepo.d/command/diff/diff.py
Per request of @aoloso, this allows one to do:
```
mepo diff <repo>
```
=> Add per-repo diff ability

mepo.d/command/whereis/whereis.py
Whereis broke with the fixes for moving repos
=> Fix whereis in develop

mepo.d/command/diff/diff.py, mepo.d/command/whereis/whereis.py
Some fixes for whereis and diff
=> Fixes for whereis and diff

etc/mepo-cd.zsh, mepo.d/command/diff/diff.py, mepo.d/command/whereis/whereis.py
Pulls in the bugfixes for whereis and main
=> Pull Develop into main

mepo.d/repository/git.py, mepo.d/state/component.py
Pulls in the init bugfix for fixtures.
=> GitFlow: Pull hotfix from main into develop

mepo.d/cmdline/parser.py, mepo.d/repository/git.py
I recently found a case where fetch needed `--force`. I suppose it's "safe" with fetch. I've avoided force flags elsewhere (figuring use git for that), but fetch might be okay.
=> Add force flag for fetch and fetch-all

README.md
This just gets the updated `README`
=> Pull main into develop

mepo.d/state/component.py
This seems to work in testing. Probably a bit more complicated than needed, but I learned about sets.
=> Fixes #150. Only allow tag or branch, not both

mepo.d/cmdline/parser.py
Simple change. Add `-q` flag to the `--quiet` flags.
=> Add -q flag

mepo.d/cmdline/parser.py, mepo.d/cmdline/tag_parser.py, mepo.d/command/push-all/push-all.py, mepo.d/command/tag/create/create.py, mepo.d/command/tag/delete/delete.py
Also, create a "push-all" command to push on all components
=> Allow tag create and delete to work on all comps

mepo.d/repository/git.py, mepo.d/utilities/shellcmd.py
This is for the `mepo save` fix.
=> Merge Develop into main for release

.editorconfig, .github/workflows/changelog-enforcer.yml, CHANGELOG.md
Closes #201 
This PR adds a `CHANGELOG.md` to mepo
=> Add changelog and changelog enforcer

README.md
This adds the latest zenodo badge from main
=> Merge main into develop

.github/workflows/mepo.yaml, CHANGELOG.md, mepo.d/command/diff/diff.py, mepo.d/command/status/status.py, mepo.d/repository/git.py, mepo.d/state/component.py
This is for a release of ignore_submodules work.
=> GitFlow: Merge Develop into main

.pre-commit-config.yaml, pyproject.toml, requirements-dev.lock, src/mepo/command/changed-files.py, src/mepo/command/checkout-if-exists.py, src/mepo/command/clone.py, src/mepo/command/commit.py, src/mepo/command/compare.py, src/mepo/command/develop.py, src/mepo/command/diff.py, src/mepo/command/init.py, src/mepo/command/reset.py, src/mepo/command/restore-state.py, src/mepo/command/tag_create.py, src/mepo/command/unstage.py, src/mepo/component.py, src/mepo/state.py, src/mepo/utilities/colors.py
- Added pre-commit hook to run Black
- Removed unused imports etc. to make linter a little happier
=> Some engineering

CHANGELOG.md, pyproject.toml, src/mepo/command/checkout-if-exists.py, src/mepo/command/checkout.py, src/mepo/command/clone.py, src/mepo/command/develop.py, src/mepo/command/restore-state.py, src/mepo/git.py, src/mepo/registry.py, tests/test_mepo_commands.py
=> GitFlow: Merge main into develop after hotfix

.github/workflows/run-formatter.yaml, .github/workflows/run-linter.yaml, .github/workflows/run-tests.yaml, CHANGELOG.md, pyproject.toml, tests/output/output_branch_list.txt, tests/test_mepo_commands.py
=> Fixes #358 - migrate from rye to uv

README.md
This adds a DeepSeek badge so that the site will auto-refresh [its mepo page](https://deepwiki.com/GEOS-ESM/mepo) weekly.
=> Add DeepSeek Badge
