mepo.d/command/compare/compare.py, mepo.d/repository/git.py, mepo.d/utilities/colors.py
A number of updates.
1. Use colorama in colors.py if available and add yellow
2. Make `mepo status` be more verbose by parsing the `git status --porcelain=v2` output.
Before:
```
$ mepo status
Checking status...
ESMA_env               | (t) v1.4.0 (DH)
| ?? jalsdkf
ESMA_cmake             | (t) v1.0.10 (DH)
ecbuild                | (b) origin/feature/FindMKL-portability-improvement (DH)
FMS                    | (t) geos/orphan/v1.0.3 (DH)
GMAO_Shared            | (t) v1.0.13 (DH)
FVdycoreCubed_GridComp | (t) v1.0.8 (DH)
fvdycore               | (t) geos/v1.0.2 (DH)
MAPL                   | (t) v1.1.12 (DH)
|  M GMAO_pFIO/tests/test_RequestDataMessage.pf
|  D README.md
| RD CHANGELOG.md -> yaya
| ?? bobo
```
After (there is color in this that GitHub can't see):
```
$ mepo status
Checking …
```
=> Updates to prettify status and compare

mepo.d/command/clone/clone.py, mepo.d/repository/git.py, mepo.d/state/component.py
This adds the ability to add a `recurse_submodules` line to the
`components.yaml`, e.g.:
```yaml
pfunit:
local: ./@pfunit
remote: git@github.com:Goddard-Fortran-Ecosystem/pFUnit.git
tag: v4.1.5
recurse_submodules: True
```
=> Fixes #24. Add recurse_submodules ability

mepo.d/cmdline/parser.py, mepo.d/command/checkout-if-exists/checkout-if-exists.py, mepo.d/repository/git.py, mepo.d/utilities/shellcmd.py
This command is run like:
```
mepo checkout-if-exists <branch-name>
```
It then checks every repository for that branch and if it's found, it
checks it out.
=> Fixes #33. Adds a new checkout-if-exists command

mepo.d/cmdline/parser.py, mepo.d/command/checkout-if-exists/checkout-if-exists.py
`checkout-if-exists` already had a `--verbose` flag. Now make that a `--quiet` flag and print all the times. :smile:
=> Fixes #45. Verbose checkout-if-exists

mepo.d/cmdline/parser.py, mepo.d/repository/git.py
This seems to allow both for a no-message `mepo commit` and `mepo commit -m`
My only concern is that I have to use `subprocess.call()` to get
`$EDITOR` to spawn. Sometimes call is odd...but it seems to work!
=> Fixes #44. Make mepo commit act like git commit

etc/mepo-completion.bash, mepo.d/repository/git.py, mepo.d/state/state.py
This seems to allow the ability to use relative URLs in `components.yaml` which is useful on machines that don't have SSH keys (aka docker).
Also fix a bug with sparsify (not sure how it ever worked before) and tweak the completion file.
=> Fixes #25. Allow for relative URLs in components.yaml

mepo.d/command/commit/commit.py, mepo.d/repository/git.py
This seems to allow a single EDITOR call to have a message for multiple repos
=> Fixes #48. Open one editor for multi repo commit

etc/mepo-completion.bash
If `mepo` was symlinked, you the completion didn't work. This should let
it
=> Fix completion for symlinked mepo

etc/mepo-cd.bash, mepo, mepo.d/command/whereis/whereis.py
This PR should allow `mepo-cd` alone to `cd` to the root of the project where 'root' is where `root/.mepo/` exists.
=> Fixes #57. mepo-cd alone moves to root

.github/workflows/mepo.yaml
The old GitHub actions were using v1, move to v2.
Also, build/test with Linux and macOS and Python 3.x and pypy3.
Note: I tried windows-latest as well, but it went kaboom. And as I don't have a WSL instance to play with yet, I'm removing its testing for now.
=> Update GitHub Actions

mepo.d/cmdline/parser.py, mepo.d/command/clone/clone.py, mepo.d/command/init/init.py, mepo.d/config/config_file.py, mepo.d/repository/git.py, mepo.d/state/exceptions.py, mepo.d/state/state.py, mepo.d/utest/test_mepo_commands.py
This PR is to allow `mepo` to do:
```
mepo clone URL
```
and have it do the `git clone`, then `chdir`, then run `mepo init` and then `mepo clone` all in one shot. But there are some minor changes and caveats to allow this:
* `mepo init` and `mepo clone` have a new `--config` option that will be used to specify a different `components.yaml` file. Before it was the only option, but since a URL can be passed to `clone` without a `--option`, configs lost.
* `mepo clone URL` is fragile. It seems to work with all variants of https and ssh but issues are possible.
Example:
```
❯ mepo clone git@github.com:GEOS-ESM/GEOSgcm.git
Initializing mepo using components.yaml
env                    | (t) v2.1.5
cmake                  | (t) v3.0.6
ecbuild                | (t) geos/v1.0.5
NCEP_Shared …
```
=> Fixes #73. Allow mepo clone to use a URL

mepo.d/repository/git.py, mepo.d/state/component.py
- Makes `mepo status` etc. not crash with non-tag hashes
- Allows one to specify `hash: a12345b` say in `components.yaml`
=> Fixes #75. Handle git hashes better

mepo.d/cmdline/parser.py, mepo.d/cmdline/stash_parser.py, mepo.d/command/stash/stapply/stapply.py, mepo.d/command/stash/stash.py, mepo.d/command/stash/stlist/stlist.py, mepo.d/command/stash/stpop/stpop.py, mepo.d/command/stash/stpush/stpush.py, mepo.d/repository/git.py
This PR will add four subcommands under `mepo stash`:
* `push <repo>`
* `list`
* `apply <repo>`
* `pop <repo>`
It's not perfect as you can't pass in a stash reference say, but it's a first start.
=> Fixes #8. Add basic mepo stash subcommands

mepo.d/repository/git.py
This should restore `mepo push` functionality. The problem is it was trying to push against `../ESMA_env.git` or whatever. That's not right. needs to use the resolved URL
=> Fixes #83. Fix mepo push

mepo.d/cmdline/parser.py, mepo.d/command/clone/clone.py, mepo.d/utest/test_mepo_commands.py
With this PR, you can do:
```
mepo clone -b tag URL
```
which is like:
```
git clone URL
cd 
git checkout tag
mepo init && mepo clone
```
ETA: Also added ability to do:
```
mepo clone URL directory
```
and even:
```
mepo clone -b tag URL directory
```
=> Fixes #86. Add clone branch of URL and directory

mepo, mepo.d/cmdline/parser.py, mepo.d/command/fetch-all/fetch-all.py, mepo.d/command/pull-all/pull-all.py, mepo.d/command/pull/pull.py
This PR adds (per request of @sdrabenh):
- `mepo pull`
- `mepo pull-all`
- `mepo fetch-all`
Note that since you can't `git pull` on a detached HEAD state, the `pull-all` will only pull on real branches. The others will spit out as a print:
```
❯ mepo pull-all
Pulling branch throw-away in ESMA_env
The following repos were not pulled (detached HEAD): ESMA_cmake, ecbuild
```
Also fixes the `mepo` file as, on Darwin, things went kablooey recently with Python 3.8
=> Fixes #70. Add mepo pull, pull-all, fetch-all

mepo.d/cmdline/parser.py, mepo.d/command/revert/revert.py
With this new `mepo revert` command, you should be able to revert a checkout to what the original state was. This was a request/idea inspired by @yvikhlya:
```
❯ mepo compare
Repo       | Original             | Current
---------- | -------------------- | -------
ESMA_env   | (t) v2.1.6 (DH)      | (b) feature/mathomp4/intel1912
ESMA_cmake | (t) v3.1.2 (DH)      | (t) v3.1.2 (DH)
ecbuild    | (t) geos/v1.0.5 (DH) | (t) geos/v1.0.5 (DH)
❯ mepo revert
Checking status...
Reverting ESMA_env to v2.1.6
❯ mepo compare
Repo       | Original             | Current
---------- | -------------------- | -------
ESMA_env   | (t) v2.1.6 (DH)      | (t) v2.1.6 (DH)
ESMA_cmake | (t) v3.1.2 (DH)      | (t) v3.1.2 (DH)
ecbuild    | (t) geos/v1.0.5 (DH) | (t) geos/v1.0.5 (DH)
```
=> Add revert command

mepo.d/cmdline/parser.py, mepo.d/command/restore-state/restore-state.py
It was remembered that `mepo` commands with the same name as a `git` command usually try to act the same. As there is already a `git revert` command, a `mepo revert` would have to have similar functionality. It doesn't.
So we rename `mepo revert` to `mepo restore-state`.
=> Change revert to restore-state

mepo.d/cmdline/branch_parser.py, mepo.d/command/branch/brlist/brlist.py
This adds the ability to do:
```
mepo branch list -a <component>
```
Before, `mepo branch list -a` did *all* components, and if there are a lot of branches, the list is long!
=> Add ability to specify a specific branch for listing

mepo.d/cmdline/parser.py, mepo.d/command/checkout-if-exists/checkout-if-exists.py
Per a request by @sdrabenh, add a `--dry-run` (also `-n`) to `checkout-if-exists` that lists where branches exist but doesn't checkout:
```
❯ mepo checkout-if-exists -n feature/mathomp4/mkl-is-optional
Branch feature/mathomp4/mkl-is-optional exists in cmake
Branch feature/mathomp4/mkl-is-optional exists in NCEP_Shared
Branch feature/mathomp4/mkl-is-optional exists in GEOSgcm_GridComp
```
=> Adds a dry-run option for checkout-if-exists

mepo.d/command/save/save.py, mepo.d/repository/git.py, mepo.d/state/component.py
Some issues were noted in trying out `mepo save`. It was saving the new yaml in the wrong place, and hashes weren't handled well.
=> Add ability to save hashes and tags to yaml

mepo.d/repository/git.py, mepo.d/state/component.py, mepo.d/state/state.py
This PR fixes #106. The issue was that full paths were hardcoded into the mepo state at initialization time. Instead, we now store local/relative paths and then do operations on full paths relative to where the `.mepo/` directory is.
=> Fixes #106. Allow mepo fixtures to be moved

mepo.d/command/compare/compare.py, mepo.d/command/diff/diff.py, mepo.d/command/status/status.py, mepo.d/utilities/version.py
This is a bit of "nicety" for `mepo status`. Before if you checked out a model with branches in `components.yaml` you got:
```console
❯ mepo status
Checking status...
env                    | (b) origin/feature/bmauer/updates-from-geosadas5_27_0 (DH)
cmake                  | (t) v1.0.11 (DH)
ecbuild                | (t) geos/v1.0.0 (DH)
NCEP_Shared            | (b) origin/feature/mathomp4/update-to-geosadas527 (DH)
GMAO_Shared            | (b) origin/feature/bmauer/updates-from-geosadas5_27_0 (DH)
MAPL                   | (b) origin/feature/bmauer/updates-from-geosadas5_27_0 (DH)
FMS                    | (t) geos/orphan/v1.0.3 (DH)
GEOSana_GridComp       | (b) origin/feature/mathomp4/update-to-geosadas527-withoutMAPL2changes (DH)
GEOSgcm_GridComp       | (b) …
```
=> Remove origin/ from status for clarity

etc/mepo-cd.zsh
The `mepo-cd.bash` did not work in zsh.
=> Add mepo-cd.zsh

etc/mepo-cd.csh
Adds `mepo-cd.csh` which defines a `mepo-cd` alias.
=> Add mepo-cd.csh

mepo.d/repository/git.py, mepo.d/state/component.py
Some CI systems clone things in odd ways. This fixes `mepo init` and `mepo status` to the point where they will work (on GitHub Actions at least). No regular user will ever do like they do as `git clone` is the "sane" way.
=> Fixes for CI systems that use shallow clones

mepo.d/state/component.py
This is a bug in the fixture handling. The mepo init code just assumed everything is detached, but we now have a special case that isn't true. Note this is *very* verbose in that there are a lot of `is_detached` but there is a chance I'm missing some special case.
=> mepo assumed everything is detached at init

mepo.d/cmdline/parser.py, mepo.d/repository/git.py
`mepo diff` would be served with a `--staged` option. So this adds it.
=> Add --staged option to mepo diff

mepo.d/command/clone/clone.py
I'm not sure it's perfect, but it let's it work. I wasn't sure what to do with the passed in yaml file, so I just copy it into the fixture.
=> Fixes #128. Allow all-in-one clone with a config

mepo.d/cmdline/parser.py, mepo.d/command/clone/clone.py
The last fix for cloning with config broke all-in-one cloning *without* config. Sigh. Bad Matt. This fixes that.
=> Fix for clone-config bug

mepo.d/command/save/save.py, mepo.d/repository/git.py
This is an interesting bug. So, the way mepo was figuring out what branch you were on with detached head was:
```
git show -s --pretty=%D HEAD
```
and then taking the second field. In most cases, this is fine, but sometimes you have two branches that are identical:
```console
❯ git show -s --pretty=%D HEAD
HEAD, origin/feature/wputman/dyamond_v2, origin/develop, origin/HEAD, develop
```
So, even though you checked out `develop`, `mepo status` was returning that after running `mepo clone` you were on `feature/wputman/dyamond_v2`. While this isn't incorrect, it's not quite right and mepo shows a difference.
After looking at the git source code, I think it uses the internals used for the reflog to get this. If I look at the `git-reflog` output:
```console
❯ git reflog
eb7e199 (HEAD, …
```
=> Fix bug with mepo status on odd branches

mepo.d/command/clone/clone.py, mepo.d/command/compare/compare.py, mepo.d/command/status/status.py, mepo.d/repository/git.py
Updates to mom6 exposed a bug in how mepo handles clones. This seems to fix it.
=> Fix for cloning exposed by mom6

mepo.d/cmdline/parser.py, mepo.d/command/checkout/checkout.py, mepo.d/command/develop/develop.py
This PR adds some useful prints to `mepo checkout` and `mepo develop` such that if you do:
```console
❯ mepo checkout v3.1.3 ESMA_env
Checking out v3.1.3 in ESMA_env
❯ mepo checkout -b feature/amazing ESMA_cmake
Creating and checking out branch feature/amazing in ESMA_cmake
❯ mepo develop MAPL
Checking out development branch develop in MAPL
```
Probably more places `mepo` can be verbose, but this was an easy one.
Note: I've added `--quiet` option to them to suppress prints if wanted.
=> Add useful checkout messages

mepo.d/cmdline/parser.py, mepo.d/command/init/init.py, mepo.d/command/restore-state/restore-state.py, mepo.d/command/status/status.py, mepo.d/state/component.py, mepo.d/state/state.py, mepo.d/utest/input/components.yaml, mepo.d/utest/output/compare_no_change.txt, mepo.d/utest/output/list_output.txt, mepo.d/utest/output/status_output.txt, mepo.d/utest/test_mepo_commands.py
With this PR, one can do:
```
mepo init --style <foo>
```
or:
```
mepo clone --style <foo> URL
```
and the `--style <foo>` can be one of `naked`, `prefix`, and `postfix` with the default as `prefix` as that is the current dominant style.
These styles are `prefix` leads to `@subrepo`, `postfix` leads to `subrepo@`, and `naked` leads to `subrepo` when `mepo` clones the subrepos
=> Add support for a style option for repo indicator

etc/mepoconfig-example, mepo.d/cmdline/config_parser.py, mepo.d/cmdline/parser.py, mepo.d/command/command.py, mepo.d/command/config/config.py, mepo.d/command/config/delete/delete.py, mepo.d/command/config/get/get.py, mepo.d/command/config/print/print.py, mepo.d/command/config/set/set.py, mepo.d/command/init/init.py, mepo.d/state/component.py, mepo.d/utilities/mepoconfig.py
Closes #139 
This isn't perfect, but it's a first blush at a mepoconfig capability. Thanks to @JulesKouatchou for inspiration.
To wit, this PR adds support for a `~/.mepoconfig` file and adds a new command:
```console
usage: mepo config [-h] {get,set,delete,print} ...
Runs config commands.
positional arguments:
{get,set,delete,print}
```
which has four subcommands. I tried to make it like `git-config` in many respects, but I'm not that good at Python and Argparse so it's like many other mepo commands with subcommands. 
***NOTE***: This capability is *not* as powerful as `git-config` is. For example, this:
```
[alias]
ci = commit
```
is allowed. But this:
```
[alias]
cm = commit -m
```
is not. This is a limitation of what I could do in Python and with Argparse. You can make an alias of a …
=> Add mepo config capability 

mepo.d/command/compare/compare.py, mepo.d/command/status/status.py, mepo.d/repository/git.py, mepo.d/utilities/version.py
Closes #162 
This is a first shot at trying to fix some mepo/git weirdness. This update uses `git rev-list` to try and see if two tags are the same. This can then be used in `status` and `compare` so that just in case `mepo` is seeing different tags, we can check if they point to the same commit. If they do, then we just "re-use" the original tag that `mepo clone` used.
=> Attempt to fix mepo status and compare tag weirdness

mepo.d/cmdline/parser.py, mepo.d/cmdline/tag_parser.py, mepo.d/command/push-all/push-all.py, mepo.d/command/push/push.py, mepo.d/command/tag/push/push.py, mepo.d/command/tag/tag.py, mepo.d/repository/git.py, mepo.d/utest/input/components.yaml, mepo.d/utest/output/compare_no_change.txt, mepo.d/utest/output/status_output.txt, mepo.d/utest/test_mepo_commands.py
This PR is needed to allow force pushing tags. While we don't want this it is needed for some scenarios. But, at least with this PR, you can only force push a single tag. Before when it used `git push --tags` there was a chance to screw things up as that pushes *all* tags.
Now you have to run `mepo tag push TAG [REPO]` to push a tag. Also added a `--force` flag because scary as it is, it is needed at times (otherwise people have to do scary git commands).
=> Add tag push command. Remove --tags from push

mepo.d/command/init/init.py, mepo.d/state/component.py
Until GEOS-ESM fixtures can be fixed up to support all styles, to make things easy, if no style is specified on command line or in `.mepoconfig`, just use what `components.yaml` says to do.
=> Fix default style if none specified

mepo.d/cmdline/parser.py, mepo.d/command/clone/clone.py, mepo.d/utest/input/args.py
Based on a workflow suggested by @rtodling, this PR adds a new `--allrepos` option to `mepo clone`. With this flag, not only is the tag/branch passed to the `--branch/-b` option to `mepo clone` checked out, but it also checks out that tag in *all sub repositories*!
To wit, if you do:
```
mepo clone -b <tag> --allrepos fixture-repo
```
what this will do is:
```
git clone -b fixture-repo
cd fixture-repo
mepo clone
mepo checkout <tag> [on all subrepos]
```
Note this means it will fail if the tag requested is not on all repos!
=> Add allrepos option to clone

mepo.d/cmdline/parser.py, mepo.d/command/checkout/checkout.py
In doing some experimenting, it was found that the `checkout` command sort of doesn't fit in the "allow a (safe) command to run on all repos" style of mepo (see how `fetch` was extended).
So, what this PR does is allow for `mepo checkout foo` to run on *all repos* if no component is specified. 
BUUUUUUUT, we *DO NOT ALLOW* `mepo checkout -b newbranch`. If you want to create and make a new branch, you need to do it specifically on repos. You should *think* about that one!
=> Allow checkout on all repos

mepo.d/command/clone/clone.py, mepo.d/command/save/save.py, mepo.d/repository/git.py, mepo.d/state/component.py, mepo.d/utilities/version.py
Recent developments in the GEOS repos in re tags broke `mepo save`. As this might be needed functionality soon (see #180), we need to fix it.
Also, in this PR, we allow `components.yaml` to use something like:
```yaml
ESMA_cmake:
local: ./ESMA_cmake
remote: ../ESMA_cmake.git
hash: a64765f4ddc00c62b441bb08b31585cfa645756e
develop: develop
```
This needs changes because `git clone -b hash` is not allowed. Only tags and branches (I think?) are allowed:
-b <name>, --branch <name>
Instead of pointing the newly created HEAD to the branch pointed to by the cloned repository's HEAD, point to <name> branch instead. In a non-bare repository,
this is the branch that will be checked out.  --branch can also take tags and detaches the HEAD at that commit in the resulting repository.
These updates also …
=> Fix save and allow hash in components.yaml

mepo.d/cmdline/parser.py, mepo.d/command/develop/develop.py, mepo.d/command/pull-all/pull-all.py, mepo.d/command/pull/pull.py, mepo.d/repository/git.py
The `mepo pull` command was a bit too quiet by default. You never knew if anything happened. Now it's noisy by default and can be quieted with `--quiet`
=> Make pull commands noisy by default

mepo.d/cmdline/parser.py, mepo.d/command/checkout/checkout.py
This allows `checkout -b` to be run on all repos with no repos to `mepo`
=> Allow checkout -b for all repos

mepo.d/command/clone/clone.py, mepo.d/repository/git.py, mepo.d/state/component.py, mepo.d/utest/test_mepo_commands.py
Closes #190 
The fix mainly involves using `shlex.split` when interacting with `subprocess`. Also quoting paths in a few places so `shlex` can do its thing.
Tested by:
```
mkdir ~/Directory\ With\ Spaces
cd !$
mepo clone -b feature/geos-v10.17.6/gocart2g/v2.0.0 git@github.com:GEOS-ESM/GEOSgcm.git BOBO\ JOJO\ DODO
cd !$
```
and all subcommands seem happy.
=> Fixes for handling paths with spaces

mepo.d/repository/git.py, mepo.d/utilities/shellcmd.py
Because of some stupid Linux/X11 thing, `mepo save` is broken. This fixes it.
=> Fix broken save

CHANGELOG.md, mepo.d/cmdline/parser.py, mepo.d/command/checkout-if-exists/checkout-if-exists.py, mepo.d/command/checkout/checkout.py, mepo.d/command/clone/clone.py, mepo.d/repository/git.py
This PR should detach branches when doing clone steps.
Also adds `--detach` as an option to `checkout` commands because...why not?
=> Detach branches on clone

.github/workflows/mepo.yaml, CHANGELOG.md, mepo.d/cmdline/parser.py, mepo.d/command/status/status.py, mepo.d/repository/git.py, mepo.d/utest/test_mepo_commands.py, requirements.txt
This PR adds a new option to `mepo status` and `mepo diff`. The issue is that sometimes when helping users, they need to give read permission to a model clone to get help. But if they decided to do a `chmod 777` then `git` will see all sorts of changes. For example:
```console
❯ gh repo clone GEOS-ESM/ESMA_env
❯ git -C ESMA_env status --porcelain=v2
❯ chmod -R 777 ESMA_env
❯ git -C ESMA_env status --porcelain=v2
1 .M N... 100644 100644 100755 38265f565f397fff5069aa3425289e6fa2d042f0 38265f565f397fff5069aa3425289e6fa2d042f0 .github/workflows/changelog-enforcer.yml
1 .M N... 100644 100644 100755 b25c15b81fae06e1c55946ac6270bfdb293870e8 b25c15b81fae06e1c55946ac6270bfdb293870e8 .gitignore
1 .M N... 100644 100644 100755 0c075a78b7d1eda40090ce65dbf557908a581e8b …
```
=> Add option to ignore permissions with status and diff

CHANGELOG.md, etc/mepo-cd.bash, etc/mepo-cd.csh, etc/mepo-cd.zsh, mepo.d/cmdline/parser.py, mepo.d/command/diff/diff.py, mepo.d/command/whereis/whereis.py, mepo.d/utilities/verify.py
This PR adds a new option to `mepo whereis`, `--ignore-case` (or `-i`). This option, as it says, allows for a user to ignore the case of the component for `whereis`:
```console
❯ mepo whereis mapl
Traceback (most recent call last):
File "/Users/mathomp4/bin/mepo", line 17, in <module>
main()
File "/Users/mathomp4/mepo/mepo.d/main.py", line 6, in main
command.run(args)
File "/Users/mathomp4/mepo/mepo.d/command/command.py", line 11, in run
cmd_module.run(args)
File "/Users/mathomp4/mepo/mepo.d/command/whereis/whereis.py", line 15, in run
verify.valid_components([args.comp_name], allcomps, ignore_case=args.ignore_case)
File "/Users/mathomp4/mepo/mepo.d/utilities/verify.py", line 23, in valid_components
_validate_component(component_to_find, all_component_names)
File …
```
=> Add ignore-case option to mepo whereis, update mepo-cd

CHANGELOG.md, mepo.d/command/compare/compare.py
The change to add the hashes to `mepo compare` output broke the nice looking table. This fixes that.
=> Fix mepo compare output

CHANGELOG.md, mepo.d/cmdline/parser.py, mepo.d/command/compare/compare.py
This PR changes the default behavior of `mepo compare`. Now, `mepo compare` will only show differing repos:
```
❯ mepo compare
Repo                   | Original                         | Current
---------------------- | -------------------------------- | -------
env                    | (t) v3.11.0 (DH)                 | (b) main
cmake                  | (t) v3.10.0 (DH)                 | (b) develop
MAPL                   | (t) v2.17.2 (DH)                 | (b) develop
```
To see all repos, use `--all`:
```
❯ mepo compare --all
Repo                   | Original                         | Current
---------------------- | -------------------------------- | -------
GEOSgcm                | (b) main                         | (b) main
env                    | (t) v3.11.0 (DH) …
```
=> Make compare brief by default, add --all option

CHANGELOG.md, mepo.d/cmdline/parser.py, mepo.d/repository/git.py
This PR adds a `-b`/`--ignore-space-change` flag to the `mepo diff` command, a la `git diff -b`. This allows diffing to ignore whitespace changes.
=> Add whitespace ignore to diff

.github/workflows/mepo.yaml, CHANGELOG.md, mepo.d/command/clone/clone.py, mepo.d/repository/git.py, mepo.d/state/exceptions.py, mepo.d/state/state.py
Closes #224 
This fixes a bug in mepo running `mepo clone`. First, it makes the error a bit more clear when you try to `mepo clone` in a fixture already cloned (see #224):
```console
$ mepo clone git@github.com:GEOS-ESM/MAPL.git
Initializing mepo using components.yaml
ESMA_env   | (t) v3.11.0
ESMA_cmake | (t) v3.10.0
ecbuild    | (t) geos/v1.2.0
$ cd MAPL
$ mepo clone
fatal: destination path '/Users/mathomp4/Models/MAPL/ESMA_env' already exists and is not an empty directory.
Error! Repo [ESMA_env] already cloned
```
Note it will always error out with the first repo `mepo` tries to clone again.
But, it also fixes a bug where you could re-`mepo clone` in *any subdirectory*! For example this:
```console
$ mepo clone git@github.com:GEOS-ESM/MAPL.git
Initializing mepo using components.yaml …
```
=> Fixes #224. Fix for running mepo clone more than once

CHANGELOG.md, mepo.d/repository/git.py
This PR adds support for typechange commits. At the moment, `mepo status` will say:
```
GOCART      | (b) main
| ESMF/GOCART2G_GridComp/DU2G_GridComp/AMIP.20C/DU2G_instance_DU.rc: unknown (please contact mepo maintainer)
```
because it doesn't know about this. But with this PR we can now translate those:
```
GOCART      | (b) main
| ESMF/GOCART2G_GridComp/DU2G_GridComp/AMIP.20C/DU2G_instance_DU.rc: typechange, staged but deleted, not staged
```
Note this might not be a complete support for typechange, but at least should cover the "main" commits.
=> Fixes #228. Add typechange support

CHANGELOG.md, mepo.d/cmdline/parser.py, mepo.d/command/checkout-if-exists/checkout-if-exists.py, mepo.d/repository/git.py
Closes #231 
This PR now allows for `checkout-if-exists` to work on tags or branches. For a branch:
```
❯ mepo checkout-if-exists feature/mathomp4/add-shared-baselibs-support -n
Branch feature/mathomp4/add-shared-baselibs-support exists in env
Branch feature/mathomp4/add-shared-baselibs-support exists in cmake
Branch feature/mathomp4/add-shared-baselibs-support exists in MAPL
Branch feature/mathomp4/add-shared-baselibs-support exists in GEOSgcm_GridComp
```
and for a tag:
```
❯ mepo checkout-if-exists sdr_r21c_v01 -n
Tag sdr_r21c_v01 exists in GEOSgcm_GridComp
Tag sdr_r21c_v01 exists in GEOSgcm_App
```
Before tags were just ignored.
=> Allow checkout-if-exists to work on tags

CHANGELOG.md, mepo.d/cmdline/tag_parser.py, mepo.d/command/tag/push/push.py, mepo.d/repository/git.py
This PR adds the ability do a remote tag delete with:
```
mepo tag delete tagname repo1 repo2
mepo tag push --delete tagname repo1 repo2
```
The first deletes locally and the second deletes remotely.
=> Add tag push delete

CHANGELOG.md, mepo.d/cmdline/parser.py, mepo.d/command/reset/reset.py, mepo.d/state/exceptions.py
Closes #244 
This PR adds a new `mepo reset` command:
```
❯ mepo reset -h
usage: mepo reset [-h] [-f] [--reclone] [-n]
Reset the current mepo clone to the original state.This will delete all subrepos and does not check for uncommitted changes! Must be run in the root of
the mepo clone.
options:
-h, --help     show this help message and exit
-f, --force    Force action.
--reclone      Reclone repos after reset.
-n, --dry-run  Dry-run only
```
By default, it will not re-clone a repo and will require a user to answer another question to run (without force flag):
```
❯ mepo clone
Initializing mepo using components.yaml
ESMA_env   | (t) v4.8.0
ESMA_cmake | (t) v3.21.0
ecbuild    | (t) geos/v1.3.0
❯ mepo reset
Are you sure you want to reset the project? If so, type 'yes' and press enter. yes …
```
=> Add new reset command

CHANGELOG.md, mepo.d/command/compare/compare.py, mepo.d/utest/output/compare_brief_output.txt, mepo.d/utest/output/compare_full_output.txt, mepo.d/utest/output/status_output.txt, mepo.d/utest/test_mepo_commands.py
As discovered by @pchakraborty, if an original branch name is very long, this can cause odd output of `mepo compare` on narrow (relative to the branch name) terminals. 
With this fix, `mepo compare` will use only the repos that change to figure out how wide to make the output rather than *all* the branches on all the repos.
Of course, if you do `mepo compare --all`, it will base the output on all the repos.
=> Compare headers based on changed branch length

.zenodo.json, CHANGELOG.md, mepo.d/cmdline/parser.py, mepo.d/command/status/status.py
This is useful for working repository when there's a lot of "develop" branch going on and that you don't necessarily want to tag the root component.
The hash is read on demand and not stored.
=> Add `--hashes` reading HEAD to get the current hash

CHANGELOG.md, mepo.d/command/diff/diff.py, mepo.d/command/status/status.py, mepo.d/repository/git.py, mepo.d/state/component.py
As detailed in #257, a mepo oddity occurs in GEOSgcm because of how CICE and icepack are handled. 
Technically, icepack is a submodule of CICE in the repo (see https://github.com/GEOS-ESM/CICE) and git sees it as that. However, currently GEOS handles icepack as a separate repo (most likely for ease of development) but git doesn't really know this. So when you go to CICE in GEOS in a fresh clone you see:
```
$ git status
HEAD detached at geos/v0.0.2
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   icepack (new commits)
Submodules changed but not updated:
* icepack 81a7628...8d80ff5 (1):
> Merge pull request #1 from GEOS-ESM/bugfix/zhaobin74/recompute-enthalpy
no …
```
=> Add ability to ignore submodules

CHANGELOG.md, mepo.d/command/diff/diff.py, mepo.d/command/status/status.py, mepo.d/state/component.py
It turns out changes from #260 (aka mepo v1.51.0) don't work with older mepo clones that might not have the ignore_submodules in their state. `AttributeError` galore. This fixes that.
=> Fixes for older mepo clones in re ignore_submodules

.github/workflows/mepo.yaml, CHANGELOG.md, etc/mepoconfig-example, mepo.d/cmdline/parser.py, mepo.d/command/clone/clone.py, mepo.d/repository/git.py, mepo.d/utest/test_mepo_commands.py
This PR adds support for partial clones with `mepo clone`. A new option `--partial` has two settings:
* `blobless`: performs a blobless clone via `git clone --filter=blob:none`
* `treeless`: performs a treeless clone via `git clone --filter=tree:0`
The motivation for this is that it has been noticed that clones of GEOS (mainly MAPL) are often extremely slow. For example:
```
❯ time git clone git@github.com:GEOS-ESM/MAPL.git MAPL-normal
Cloning into 'MAPL-normal'...
remote: Enumerating objects: 704212, done.
remote: Counting objects: 100% (271489/271489), done.
remote: Compressing objects: 100% (6882/6882), done.
remote: Total 704212 (delta 269709), reused 266119 (delta 264584), pack-reused 432723
Receiving objects: 100% (704212/704212), 997.08 MiB | 2.59 MiB/s, done.
Resolving deltas: …
```
=> Add support for partial clones

CHANGELOG.md, mepo.d/cmdline/parser.py, mepo.d/command/clone/clone.py
This PR adds a protection so that treeless clones do not happen when a repo has submodules. Git said that is strongly not recommended (see https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/).
Also, add a `--partial=off` option so a user can override the `.mepoconfig` behaviour.
=> Protect submodule repos from treeless, add off option

src/mepo/state/state.py
`mepo1` to `mepo2` transition includes a renaming of directories (`mepo.d` -> `src/mepo`). Since pickle requires that
> the class definition must be importable and live in the same module as when the object was stored
we need to patch `sys.modules` to be able to read `mepo1` state (https://stackoverflow.com/a/2121886)
=> Patch for reading mepo1 state

requirements-dev.lock, src/mepo/state.py
Fixed a bug where the new mepo state creation during 'mepo update-state' was following the codepath for the case when mepo state does not exist.
=> Fixed a bug in mepo state creation during 'mepo update-state'

src/mepo/cmdline/parser.py, src/mepo/command/restore-state.py, src/mepo/command/status.py, src/mepo/state.py, tests/test_mepo_commands.py
- Bugfix - convert the local path of the repos to absolute after reading the state, in case of old style state as well.
- `--serial` option for `status` and `restore-state` -  running `mepo status` on a mac seemed to cause issues for the case of an old style state. Somehow the modification of sys.modules, to be able to read `pickle`d state, do not percolate down to the processes spawned by multiprocessing. To work around this issue, added a '--serial' option to the `status` and `restore-state` commands.
=> A bug fix and '--serial' option for status and restore-state commands

CHANGELOG.md, README.md
Adds instructions for installing via `brew`
=> Add brew tap installation instructions

.github/workflows/run-tests.yaml, etc/mepo-completion.bash, etc/mepo-path.py, pyproject.toml, src/mepo/command/update-state.py, src/mepo/component.py, src/mepo/git.py, tests/test_component.py, tests/test_mepo_commands.py, tests/test_registry.py
- Full path of remote url is now stored in the state file
- Logic to decorate local path based on input `comp style` is moved to a separate function
- Added `pytest`s for Registry and MepoComponent. `pytest` is now a dev dependency in `pyproject.toml`
- Removed MepoState dependence of `git.py`
- Fixed mepo completion
=> Store complete remote url in state file

CHANGELOG.md, src/mepo/command/status.py, tests/test_mepo_commands.py
Closes #326 
This PR adds a number of stashes indicator to `mepo status`:
```
GEOSchem_GridComp      | (t) v1.14.0 (DH) [stashes: 1]
HEMCO                  | (t) geos/v2.2.3 (DH) [stashes: 1]
geos-chem              | (t) geos/v13.0.0-rc1 (DH)
GOCART                 | (t) sdr_v2.2.1.2 (DH)
QuickChem              | (t) v1.0.0 (DH)
TR                     | (t) v1.2.0 (DH)
GMI                    | (t) v1.3.0 (DH) [stashes: 2]
StratChem              | (t) v1.0.0 (DH)
```
=> Add stash indicator to status

src/mepo/git.py, tests/test_mepo_clone.py
Fix for #330 
- Added the needed space for `--recurse-submodules`
- Update `clone` test where the fixture being cloned has a component with submodules
=> Bug fix in git.py::clone - added space for --recurse-submodules

CHANGELOG.md, pyproject.toml, src/mepo/command/clone.py, tests/input/external-components.yaml, tests/output/output_branch_list.txt, tests/test_mepo_clone.py, tests/test_mepo_commands.py
Fixed bugs in
- `mepo clone --allrepos`
- `mepo clone --registry`
Created tests to cover these cases
=> Fixes for less used options of "mepo clone"

CHANGELOG.md, mepo.d/command/status/status.py
It was noticed at NAS that `mepo status` was causing fork-bomb like behavior due to weirdness with Python multiprocessing. Since `mepo status` doesn't really require parallel-ness, we move to serial by default.
This change is essentially a copy of the work of @pchakraborty as seen in the `mepo status --serial` option in mepo v2. 
Since mepo v1 is nigh-dead code, I have not implemented a `--parallel` option here. In the end, it doesn't matter since mepo v2 is just better.
=> v1: Make mepo status serial by default

CHANGELOG.md, pyproject.toml, src/mepo/command/clone.py, tests/input/external-components.yaml, tests/output/output_branch_list.txt, tests/test_mepo_clone.py, tests/test_mepo_commands.py
By hand merge of `main` into `develop` as of 2025-Jan-06
=> Merge develop into main - 2025Jan06

CHANGELOG.md, src/mepo/cmdline/parser.py, src/mepo/command/restore-state.py, src/mepo/command/status.py, tests/test_mepo_clone.py, tests/test_mepo_commands.py
Closes #337 
As described in #336, `mepo status` in its parallel version was causing fork-bomb-like behavior at NAS. As the parallel version of `status` isn't really that needed on most systems, we instead move to the serial version by default. At the same time, we remove the `--serial` flag and add a `--parallel` flag to allow users to use the old behavior if needed.
I also saw that `restore-state` had a serial/parallel version. So, for completeness, I moved that to serial by default. 
I'm keeping this PR as draft because I know @pchakraborty has tests he does locally with rye, etc. that I haven't quite learned how to do yet.
=> v2: Default status and restore-state to serial

README.md
Was fiddling around with `uv` this weekend. So I added some bits and pieces for using `mepo` with it. I added sections for `uv install` and `uvx` (aka `uv tool run`). 
I suppose there is also `uv tool install`. Not sure if we should add that or not. Maybe? I'll talk with @pchakraborty
=> Add README info for uv

CHANGELOG.md, pyproject.toml, src/mepo/registry.py, tests/test_mepo_commands.py
Closes #355 
This PR allow for fixtures to not have a `develop:` key in `components.yaml`.
I'm keeping draft as for some reason `rye test` isn't working for me locally, so I want @pchakraborty to double check.
Also, maybe a test should be added to test this situation? Dunno if it's worth that...
=> Fixes #355. Allow for fixture without develop key

CHANGELOG.md, src/mepo/cmdline/parser.py, src/mepo/command/clone.py, src/mepo/component.py, tests/output/output_branch_list.txt, tests/test_component.py
Closes #347 
This PR adds the ability to have in `components.yaml` something like:
```yaml
MAPL:
local: ./src/Shared/@MAPL
remote: ../MAPL.git
tag: v2.55.0
develop: develop
blobless: true
```
where that last option is new. This can be used for repos which are either very slow (MAPL) or are very large (ncar_topo) and so blobless clones are more a requirement than a recommendation.
=> Fixes #347. Add blobless option to components.yaml
